# -*- coding: utf-8 -*-
"""Parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DKZeSwbqtjMQOsCCkMpDAxkyerlfVbkY
"""

import os
import glob
import pandas as pd
import xml.etree.ElementTree as ET

def xml_to_csv(path):
    xml_list = []

    #for xml_file in glob.glob(path + '/*.xml'):
    for xml_file in os.listdir(path):
        if xml_file.endswith('.xml'): 
            ShotFile = os.path.join(path, xml_file)
            tree = ET.parse(ShotFile)
            root = tree.getroot()
            for member in root.findall('object'):
                bbx = member.find('bndbox')
                xmin = int(bbx.find('xmin').text)
                ymin = int(bbx.find('ymin').text)
                xmax = int(bbx.find('xmax').text)
                ymax = int(bbx.find('ymax').text)
                label = member.find('action').text

                value = (root.find('filename').text,
                        int(root.find('size')[0].text),
                        int(root.find('size')[1].text),
                        label,
                        xmin,
                        ymin,
                        xmax,
                        ymax
                        )
                xml_list.append(value)
                #print(xml_list)
                column_name = ['filename', 'width', 'height',
                      'action', 'xmin', 'ymin', 'xmax', 'ymax']
                xml_df = pd.DataFrame(xml_list, columns=column_name)

    return xml_df


def main():
        image_path = "/content/drive/MyDrive/CV_Project/Dataset/XMLAnnotations"
        xml_df = xml_to_csv(image_path)
        xml_df.to_csv('/content/drive/MyDrive/CV_Project/Dataset/annotations.csv', index=True)
        print('Successfully converted xml to csv.')


main()

